-- Chinook Database Schema (simplified for cdstore example)
-- Based on https://github.com/lerocha/chinook-database

CREATE TABLE IF NOT EXISTS artist
(
    artist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS album
(
    album_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    artist_id INT NOT NULL REFERENCES artist(artist_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS media_type
(
    media_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS track
(
    track_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    album_id INT REFERENCES album(album_id),
    media_type_id INT NOT NULL REFERENCES media_type(media_type_id),
    genre_id INT REFERENCES genre(genre_id),
    composer TEXT,
    milliseconds INT NOT NULL,
    bytes INT,
    unit_price NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS playlist
(
    playlist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS playlist_track
(
    playlist_id INT NOT NULL REFERENCES playlist(playlist_id),
    track_id INT NOT NULL REFERENCES track(track_id),
    PRIMARY KEY (playlist_id, track_id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS album_artist_id_idx ON album (artist_id);
CREATE INDEX IF NOT EXISTS track_album_id_idx ON track (album_id);
CREATE INDEX IF NOT EXISTS track_genre_id_idx ON track (genre_id);
CREATE INDEX IF NOT EXISTS playlist_track_playlist_id_idx ON playlist_track (playlist_id);
CREATE INDEX IF NOT EXISTS playlist_track_track_id_idx ON playlist_track (track_id);
